a = int(3)
b = float(2.5)
c = str("Rafael")
print(f"a = {a}, b = {b}, c = {c}")
print(f"a + b = {a+b}")
print(f"a - b = {a-b}")
print(f"a / b = {a/b}")
print(f"a elevado na 2a potência é = {a**2}")
print(f"Divisão inteira: a / b = {a//b}")
print(f"Resto de a / 2 = {a%2}")
print(f"a é igual a b? {a == b}")
print(f"a é maior que b? {a >= b}")
print(f"a é menor que b? {a <= b}")
print(f"a é diferente de b? {a != b}")

