n = int(input('Digite um número de 0 a 9999: '))
print('unidade: {}'.format((n//1)-((n//10)*10)))
print('dezena: {}'.format((n//10)-((n//100)*10)))
print('centena: {}'.format((n//100)-((n//1000)*10)))
print('milhar: {}'.format(n//1000))
p = str(input('Digite um número de 0000 a 9999 (use os 4 dígitos): '))
p = p.strip()
print('unidade: {}'.format(p[3]))
print('dezena: {}'.format(p[2]))
print('centena: {}'.format(p[1]))
print('milhar: {}'.format(p[0]))
